all: module.a

CXXFLAGS += -Wall -Wextra -fsanitize=address,fuzzer -std=c++20 -I ../../include

AES_LIB_PATH := ./aes_lib/target/release/libaes_lib.a

$(AES_LIB_PATH):
	cd aes_lib && \
	RUSTFLAGS="\
		-Z sanitizer=address \
		-C passes=sancov-module \
		-C llvm-args=-sanitizer-coverage-inline-8bit-counters \
		-C llvm-args=-sanitizer-coverage-trace-compares \
		-C llvm-args=-sanitizer-coverage-pc-table \
		-C llvm-args=-sanitizer-coverage-level=4 \
		-C llvm-args=-simplifycfg-branch-fold-threshold=0" \
	cargo +nightly build --release

cargo: $(AES_LIB_PATH)

module.a: module.o $(AES_LIB_PATH)
	bash ../../scripts/merge.sh module.a $(AES_LIB_PATH) module.o
	ranlib module.a

module.o: module.cpp module.h
	$(CXX) $(CXXFLAGS) -I . -fPIC -c module.cpp -o module.o

format:
	$(CLANG_FORMAT) -i ./module.cpp ./module.h ./aes_lib/aes_lib.h
	cd aes_lib && cargo fmt

check-format:
	$(CLANG_FORMAT) -Werror --fail-on-incomplete-format -n ./module.cpp ./module.h ./aes_lib/aes_lib.h
	cd aes_lib && cargo fmt --check

clean:
	rm -rf *.o module.a
	cd aes_lib && cargo clean

.PHONY: all cargo clean format check-format $(AES_LIB_PATH)
