[lib]
name = "entropylab_fuzz_lib"
crate-type = ["staticlib"]

[package]
name = "entropylab_fuzz_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "=0.29.1", default-features = false, features = ["std", "lowmemory"] }
bitcoin_hashes = { version = "=0.14.101", default-features = false, features = ["alloc"] }
bitcoin = { version = "=0.32.11", default-features = false, features = ["std", "secp-lowmemory"] }
bip39 = { version = "=2.2.2", default-features = false }
miniscript = { version = "=13.1.0", default-features = false, features = ["std"] }
base58ck = { version = "=0.1.101", default-features = false, features = ["std"] }
bech32 = { version = "=0.11.1", default-features = false, features = ["alloc"] }
scrypt = { version = "=0.12.0", default-features = false }
aes = { version = "=0.8.4", default-features = false, features = ["hazmat"] }
blake2 = { version = "=0.10.6", default-features = false }
constant_time_eq = { version = "=0.4.2", default-features = false }
